### ISSUE TITLE
As IDEM proxy I want to call greenID's API so that I can send users' claims to them and get the verification results

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/proxy.idem.com.au#78] opened 2022-09-13 05:50 UTC
## AC1: send users' info
- Given the user had clicked the "Verify my claims" button
- When I receive the claims
- Then I call greenID's API (background check v3)
- And I send the user's details to greenID
---
## AC2: show verification status
-  Given greenID returns the verification result
- When I receive the result
- Then IDEM app will show the verification status on the profile page

Here is the link to the results of verification status: https://vixverify.atlassian.net/wiki/spaces/GREEN/pages/60369524/Data+Structures+V3#DataStructuresV3-VerificationResultV3

**Comment by TomDodson** [comment] 2022-09-13 13:55
@jinggg-y @JasminFarhi am going to close this because it is a duplicate of this herehttps://github.com/dltxio/proxy.idem.com.au/issues/59

**Closed** 2022-09-14 00:56 UTC
Labels: High, greenID
